### PR TITLE
Save Family and Show all

### PR DESCRIPTION
**Pull request by baichuan1**
Save Family and Show all families

### CODE REVIEW

**Review by johngtoop — CHANGES_REQUESTED** [review]
Looks good! Could you add documentation for the functions @baichuan1 when you get time? What about echo something for invalid?

**Review by baichuan1 — COMMENTED** [review]
Is that enough documentation @johngtoop ?

**Comment by baichuan1** [comment]
I think I've got it @johngtoop

**Comment by johngtoop** [comment]
Like that documentation @baichuan1

**Pull request merged**
